spring:
  application:
    name: grupo14
  datasource:
    url: jdbc:mysql://localhost:3306/bd-grupo14
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false