spring:
  application:
    name: grupo-14-OO2-2024
  datasource:
    url: jdbc:mysql://localhost:3306/bd-grupo-14-OO2-2024
    username: root
    password: 42359488
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false